enableStrictSsl: false

yarnPath: .yarn/releases/yarn-3.6.4.cjs

nodeLinker: pnp
pnpMode: strict

enableStrictSsl: false

yarnPath: .yarn/releases/yarn-3.6.4.cjs

supportedArchitectures:
  os:
    - 'current'
    - 'darwin'
    - 'linux'
  cpu:
    - 'current'
    - 'x64'
    - 'arm64'
  libc:
    - 'current'
    - 'glibc'
    - 'musl'